import {
    Brain,
    Cloud,
    Code,
    Globe,
    Palette,
    Rocket,
    Shield,
    Smartphone,
    Zap
} from "lucide-react";


export const services = [
  {
    icon: Code,
    title: "Web Development",
    shortDescription:
      "Custom websites and web applications built with modern technologies.",
    longDescription:
      "We create responsive, fast, and scalable web applications using cutting-edge technologies. Our development process ensures your website is visually stunning, performs seamlessly across devices, and is optimized for security and speed.",
    features: [
      "React/Next.js Development",
      "Node.js Backend Services",
      "TypeScript Implementation",
      "GraphQL API Integration",
      "Database Design & Optimization",
      "Progressive Web Apps",
      "SEO Implementation",
      "Security Best Practices",
    ],
    process: [
      "Requirements Analysis",
      "Technical Architecture",
      "Development & Testing",
      "Deployment & Launch",
    ],
    pricing: "Starting from $5,000",
    timeline: "4-12 weeks",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: Palette,
    title: "UI/UX Design",
    shortDescription:
      "Intuitive, user-centered interfaces for exceptional experiences.",
    longDescription:
      "Our design team crafts visually stunning and intuitive interfaces that prioritize usability, accessibility, and user engagement. We focus on creating designs that drive conversions and delight users across all platforms.",
    features: [
      "User Research & Analysis",
      "Wireframing & Prototyping",
      "Figma Design Systems",
      "Interactive Prototypes",
      "Usability Testing",
      "Responsive Design",
      "Accessibility Compliance (WCAG)",
      "Design Documentation",
    ],
    process: [
      "User Research",
      "Design Strategy",
      "Visual Design",
      "Testing & Iteration",
    ],
    pricing: "Starting from $3,000",
    timeline: "3-8 weeks",
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
  },
  {
    icon: Rocket,
    title: "Brand Identity",
    shortDescription:
      "Memorable brand packages that resonate with your audience.",
    longDescription:
      "We build strong brand identities that foster recognition and trust. Our comprehensive packages include logo design, brand guidelines, and marketing materials tailored to your business’s unique story and goals.",
    features: [
      "Logo Design & Variations",
      "Brand Guidelines",
      "Color Palette Development",
      "Typography Selection",
      "Business Card Design",
      "Marketing Collateral",
      "Digital Asset Library",
      "Brand Strategy Consulting",
    ],
    process: [
      "Brand Discovery",
      "Concept Development",
      "Design Refinement",
      "Final Delivery",
    ],
    pricing: "Starting from $2,500",
    timeline: "2-6 weeks",
    color: "text-green-500",
    bgColor: "bg-green-500/10",
  },
  {
    icon: Zap,
    title: "Performance Optimization",
    shortDescription:
      "Lightning-fast websites optimized for SEO and conversions.",
    longDescription:
      "We enhance your website’s performance to ensure fast load times, high search engine rankings, and superior user experiences. Our strategies focus on speed, SEO, and Core Web Vitals to maximize conversions.",
    features: [
      "PageSpeed Insights Optimization",
      "Core Web Vitals Improvement",
      "SEO Audits & Optimization",
      "Image & Asset Compression",
      "Caching Implementation",
      "CDN Configuration",
      "Performance Monitoring",
      "Analytics Integration",
    ],
    process: [
      "Performance Audit",
      "Optimization Strategy",
      "Implementation",
      "Monitoring & Reporting",
    ],
    pricing: "Starting from $1,500",
    timeline: "1-4 weeks",
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Globe,
    title: "E-commerce Solutions",
    shortDescription:
      "Secure, scalable online stores that drive sales.",
    longDescription:
      "We develop robust e-commerce platforms with seamless payment processing, inventory management, and user-friendly interfaces. Our solutions are designed to scale with your business and optimize conversions.",
    features: [
      "Shopify/WooCommerce Development",
      "Stripe/PayPal Integration",
      "Headless CMS Implementation",
      "Inventory Management Systems",
      "Customer Account Portals",
      "Mobile-Responsive Stores",
      "SSL Security Implementation",
      "E-commerce Analytics",
    ],
    process: [
      "Store Planning",
      "Development & Integration",
      "Testing & Security",
      "Launch & Training",
    ],
    pricing: "Starting from $8,000",
    timeline: "6-16 weeks",
    color: "text-red-500",
    bgColor: "bg-red-500/10",
  },
  {
    icon: Smartphone,
    title: "Mobile Development",
    shortDescription:
      "Engaging mobile apps for iOS, Android, and cross-platform.",
    longDescription:
      "We create high-performance mobile apps tailored to your needs, offering native and cross-platform solutions. Our apps deliver seamless user experiences and are optimized for performance and discoverability.",
    features: [
      "iOS Development (Swift)",
      "Android Development (Kotlin)",
      "React Native Cross-Platform",
      "App Store Optimization",
      "Push Notification Systems",
      "Offline Functionality",
      "API Integrations",
      "App Analytics",
    ],
    process: [
      "App Strategy",
      "Design & Development",
      "Testing & QA",
      "App Store Submission",
    ],
    pricing: "Starting from $10,000",
    timeline: "8-20 weeks",
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
  },
  {
    icon: Cloud,
    title: "Cloud Solutions",
    shortDescription:
      "Scalable and secure cloud infrastructure for your business.",
    longDescription:
      "We design and deploy cloud-based solutions to ensure scalability, reliability, and cost-efficiency. From serverless architectures to CI/CD pipelines, we empower your business with modern cloud technologies.",
    features: [
      "AWS/Azure/GCP Deployment",
      "Serverless Architecture",
      "Microservices Design",
      "CI/CD Pipeline Setup",
      "Cloud Security",
      "Database Migration",
      "Cost Optimization",
      "Monitoring & Alerts",
    ],
    process: [
      "Cloud Strategy",
      "Architecture Design",
      "Implementation & Testing",
      "Ongoing Management",
    ],
    pricing: "Starting from $6,000",
    timeline: "4-10 weeks",
    color: "text-teal-500",
    bgColor: "bg-teal-500/10",
  },
  {
    icon: Shield,
    title: "Cybersecurity",
    shortDescription:
      "Robust security measures to protect your digital assets.",
    longDescription:
      "Our cybersecurity services safeguard your applications and data with comprehensive audits, secure coding practices, and ongoing monitoring to protect against threats and ensure compliance.",
    features: [
      "Penetration Testing",
      "SSL/TLS Implementation",
      "Data Encryption",
      "Compliance Audits (GDPR, HIPAA)",
      "Firewall Configuration",
      "Vulnerability Assessments",
      "Security Training",
      "Incident Response",
    ],
    process: [
      "Security Assessment",
      "Strategy & Planning",
      "Implementation",
      "Monitoring & Support",
    ],
    pricing: "Starting from $4,000",
    timeline: "3-8 weeks",
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
  },
  {
    icon: Brain,
    title: "AI Integration",
    shortDescription:
      "Smart features to enhance your applications with AI.",
    longDescription:
      "We integrate AI-driven features like chatbots, personalization, and data analytics to make your applications smarter and more engaging, leveraging machine learning and natural language processing.",
    features: [
      "Machine Learning Models",
      "AI Chatbot Development",
      "Personalization Engines",
      "Natural Language Processing",
      "Predictive Analytics",
      "AI API Integration",
      "Model Training",
      "Performance Monitoring",
    ],
    process: [
      "AI Strategy",
      "Model Development",
      "Integration & Testing",
      "Deployment & Optimization",
    ],
    pricing: "Starting from $7,000",
    timeline: "6-14 weeks",
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
  },
];

export const portfolioItems = [
  {
    id: 1,
    title: "TechFlow SaaS Platform",
    category: "web-development",
    description:
      "A comprehensive SaaS platform for project management with real-time collaboration features.",
    longDescription:
      "Built a complete project management SaaS platform with real-time collaboration, file sharing, time tracking, and advanced analytics. The platform serves over 10,000 users and handles millions of tasks.",
    image: "/api/placeholder/800/600",
    technologies: [
      "Next.js",
      "TypeScript",
      "PostgreSQL",
      "Redis",
      "WebSocket",
      "Stripe",
    ],
    liveUrl: "https://techflow.example.com",
    githubUrl: "https://github.com/example/techflow",
    year: "2024",
    client: "TechFlow Inc.",
    duration: "12 weeks",
    teamSize: "5 members",
    awards: ["Best SaaS Design 2024"],
    results: {
      userGrowth: "300%",
      performanceImprovement: "60%",
      conversionRate: "25%",
    },
  },
  {
    id: 2,
    title: "EcoMart E-commerce",
    category: "web-development",
    description:
      "Sustainable e-commerce platform with advanced filtering and recommendation system.",
    longDescription:
      "Created a modern e-commerce platform focused on sustainable products with AI-powered recommendations, advanced filtering, and seamless checkout experience.",
    image: "/api/placeholder/800/600",
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "Stripe",
      "AWS",
      "ElasticSearch",
    ],
    liveUrl: "https://ecomart.example.com",
    githubUrl: "https://github.com/example/ecomart",
    year: "2023",
    client: "EcoMart",
    duration: "16 weeks",
    teamSize: "6 members",
    awards: ["E-commerce Excellence Award"],
    results: {
      salesIncrease: "150%",
      pageLoadSpeed: "2.1s",
      customerSatisfaction: "95%",
    },
  },
  {
    id: 3,
    title: "MindSpace Mobile App",
    category: "mobile",
    description:
      "Mental health and wellness mobile app with guided meditation and mood tracking.",
    longDescription:
      "Designed and developed a comprehensive mental health app featuring guided meditations, mood tracking, progress analytics, and community support features.",
    image: "/api/placeholder/800/600",
    technologies: [
      "React Native",
      "Node.js",
      "PostgreSQL",
      "Firebase",
      "Stripe",
    ],
    liveUrl: "https://apps.apple.com/mindspace",
    githubUrl: "https://github.com/example/mindspace",
    year: "2023",
    client: "MindSpace Wellness",
    duration: "20 weeks",
    teamSize: "4 members",
    awards: ["Best Health App 2023"],
    results: {
      downloads: "100K+",
      userRetention: "85%",
      appRating: "4.8/5",
    },
  },
  {
    id: 4,
    title: "Luxe Brand Identity",
    category: "design",
    description:
      "Complete brand identity and design system for luxury fashion brand.",
    longDescription:
      "Created a comprehensive brand identity for a luxury fashion brand including logo design, brand guidelines, packaging design, and digital brand assets.",
    image: "/api/placeholder/800/600",
    technologies: ["Figma", "Adobe Creative Suite", "Sketch", "InVision"],
    liveUrl: "https://luxefashion.example.com",
    githubUrl: "#",
    year: "2024",
    client: "Luxe Fashion House",
    duration: "8 weeks",
    teamSize: "3 members",
    awards: ["Design Excellence Award"],
    results: {
      brandRecognition: "200%",
      customerEngagement: "180%",
      salesImpact: "120%",
    },
  },
  {
    id: 5,
    title: "FinTech Dashboard",
    category: "web-development",
    description:
      "Advanced financial analytics dashboard with real-time data visualization.",
    longDescription:
      "Built a sophisticated financial dashboard for investment management with real-time market data, portfolio analytics, and risk assessment tools.",
    image: "/api/placeholder/800/600",
    technologies: [
      "React",
      "D3.js",
      "Python",
      "FastAPI",
      "PostgreSQL",
      "WebSocket",
    ],
    liveUrl: "https://fintech-dashboard.example.com",
    githubUrl: "https://github.com/example/fintech",
    year: "2023",
    client: "InvestTech Solutions",
    duration: "14 weeks",
    teamSize: "7 members",
    awards: ["FinTech Innovation Award"],
    results: {
      dataProcessing: "10x faster",
      userProductivity: "40%",
      decisionSpeed: "60%",
    },
  },
  {
    id: 6,
    title: "EduLearn Platform",
    category: "web-development",
    description:
      "Interactive online learning platform with video streaming and progress tracking.",
    longDescription:
      "Developed a comprehensive e-learning platform with video streaming, interactive quizzes, progress tracking, and certification management for online education.",
    image: "/api/placeholder/800/600",
    technologies: [
      "Next.js",
      "Node.js",
      "MongoDB",
      "AWS S3",
      "Stripe",
      "Socket.io",
    ],
    liveUrl: "https://edulearn.example.com",
    githubUrl: "https://github.com/example/edulearn",
    year: "2024",
    client: "EduLearn Academy",
    duration: "18 weeks",
    teamSize: "8 members",
    awards: ["EdTech Excellence Award"],
    results: {
      studentEnrollment: "500%",
      completionRate: "78%",
      userEngagement: "300%", 
    },
  },
];
